config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :opinions
  resources :cards,  only: [:show] do
    resources :opinions, only: [:create, :show, :update, :index, :new]
  end
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord

  has_many :opinions, dependent: :destroy
  has_many :users, through: :opinions

  validates :description, presence: true
  validates :candidate, presence: true
  validates :category, presence: true


end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :card
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :opinions, dependent: :destroy
  has_many :cards, through: :opinions

  validates :age, presence: true
  validates :job, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  before_filter :update_sanitized_params, if: :devise_controller?

def update_sanitized_params
  devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:email, :password, :age, :job)}
end



end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:description, :candidate, :category)
    end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  # before_action :set_opinion, only: [:show, :edit, :update, :destroy]

  # GET /opinions
  # GET /opinions.json
  def index
    @opinions = Opinion.all
  end

  # GET /opinions/1
  # GET /opinions/1.json
  def show
  end

  # GET /opinions/new
  def new
    @card = Card.find(params[:card_id])


  end

  # GET /opinions/1/edit
  def edit
  end

  # POST /opinions
  # POST /opinions.json
  def create
    @card = Card.find(params[:card_id])
    @opinion = Opinion.new
    @opinion.user_id = current_user.id
    @opinion.card = Card.find(params[:card_id])
    @opinion.rate = params[:rate]
    respond_to do |format|
      if @opinion.save
        format.html { redirect_to "http://localhost:3000/cards/29/opinions/new" }
        format.json { render :show, status: :created, location: @opinion }
      else
        format.html { render :new }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end

  end


  # PATCH/PUT /opinions/1
  # PATCH/PUT /opinions/1.json
  def update

    @card = Card.find(params[:card_id])
    @opinion = Opinion.new
    @opinion.user_id = current_user.id
    @opinion.card = Card.find(params[:card_id])
    @opinion.rate = params[:rate]
    @opinion.save

    a = []
    @opinion.each do |opinion|
      a << opinion.card_id
    end
    a << params[:card_id]

    respond_to do |format|

        format.html { redirect_to new_card_opinion_path(card_id: ([*6..117] - a).sample) }
        format.json { render :show, status: :ok, location: @opinion }

    end
  end

  # DELETE /opinions/1
  # DELETE /opinions/1.json
  def destroy
    @opinion.destroy
    respond_to do |format|
      format.html { redirect_to opinions_url, notice: 'Opinion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_opinion
      @opinion = Opinion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def opinion_params
    #   params.require(:opinion).permit(:rate)
    # end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cards/_form.html.erb
<%= simple_form_for(@card) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.input :candidate %>
    <%= f.input :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Candidate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.description %></td>
        <td><%= card.candidate %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>Ajouter une mesure politique à l'agorithme</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @card.description %>
</p>

<p>
  <strong>Candidate:</strong>
  <%= @card.candidate %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <!-- Google result text-->
    <title>Mon Politique</title>
    <!-- Google result description-->
    <meta name="description" content="Le test complet pour découvrir rapidement les programmes des candidats et déterminer celui qui est fait pour vous.">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="Mon Politique" />
    <meta property="og:type" content="website" />
    <meta property="og:image" content="elysee.jpg" />
<!--     <meta property="og:description" content="Le test complet pour découvrir rapidement les programmes des candidats et déterminer celui qui est fait pour vous." /> -->
    <meta property="og:site_name" content="Mon Politique" />


    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-80949517-3', 'auto');
  ga('send', 'pageview');

</script>

app/views/opinions/_form.html.erb
<%= simple_form_for [@card, @opinion] do |f| %>
  <%= f.error_notification %>

<%= f.input :rate, collection: -2..2, prompt: "Nb of stars", selected: 3 %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/opinions/edit.html.erb
<h1>Editing Opinion</h1>

<%= render 'form', opinion: @opinion %>

<%= link_to 'Show', @opinion %> |
<%= link_to 'Back', opinions_path %>

app/views/opinions/new.html.erb
<div class="banner" style="background-color: #57D1C9; background-position: center; height: 100vh;">


<div class="card card-flexbox">
    <div class="card-face card-front">
      <div class="card-wrapper">
        <div class="card-left-bar "></div>
        <p class="card-day-title " style="font-color: #57D1C9;">
          <%= link_to "DECOUVREZ VOTRE CANDIDAT ICI", opinions_path, {class: "card-day-title"} %>
        </p>
        <div class="card-content" style="touch-action: manipulation; user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);">
        <div>
             <h1 style="margin-top:1em; margin-bottom: 1em; width:10em;"> <%= @card.category %> </h1>
        </div>
        <div style="text-align: left;">
        <ul>
          <% content = @card.description.split(".") %>
          <% content.each do |mesure| %>
          <li style="margin-top:10px;"> <%= mesure + "." %>  </li>

          <% end %>
        </ul>
        </div>
          <div class="flex-item">


        </div>
        <div style="margin-top: 2em;">
          <%= link_to "TRES DEFAVORABLE", new_card_opinion_path(card_id: @card.id, rate: -2), method: :patch, class: "activity-btn activity-btn-medium activity-btn-lg", style: "border-radius : 2px; background-color: #FF2E63" %>
          <%= link_to "DEFAVORABLE", new_card_opinion_path(card_id: @card.id, rate: -1), method: :patch, class: "activity-btn activity-btn-medium activity-btn-lg", style: "border-radius : 2px; background-color: #FF2E63;" %>
          <%= link_to "NEUTRE", new_card_opinion_path(card_id: @card.id, rate: 0), method: :patch, class: "activity-btn activity-btn-medium activity-btn-lg", style: "border-radius : 2px; background-color: #FF2E63;" %>
          <%= link_to "FAVORABLE", new_card_opinion_path(card_id: @card.id, rate: 1), method: :patch, class: "activity-btn activity-btn-medium activity-btn-lg", style: "border-radius : 2px; background-color: #FF2E63;" %>
          <%= link_to "TRES FAVORABLE", new_card_opinion_path(card_id: @card.id, rate: 2), method: :patch, class: "activity-btn activity-btn-medium activity-btn-lg", style: "border-radius : 2px; background-color: #FF2E63;" %>
        </div>
      </div>
    </div>


</div>

app/views/opinions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @opinion.user_id %>
</p>

<p>
  <strong>Card:</strong>
  <%= @opinion.card.description %>
</p>

<%= link_to 'Edit', edit_opinion_path(@opinion) %> |
<%= link_to 'Back', opinions_path %>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path('elysee.jpg') %>'); background-position: center;  height: 100vh;">
  <div class="banner-content flexbox">
    <div class="landing-banner-content" style="margin-top: 3em;">
        <h1 class="home-title">1 élection, 11 programmes </h1>
        <!--  <div class="landing-banner-title">
          <div id="first-group">
            <h3 id="first-group">Découvre le ici  </h3>
          </div>
         <<div id="second-group">
            <h3 id="word-roll" class="second-group">un footing !</h3>
          </div> -->
    </div>
    <div class="call-to-action" style="margin-top: -12em;">
      <%= link_to "DECOUVREZ VOTRE CANDIDAT ICI", new_card_opinion_path(card_id: rand(6..117)), {class: "activity-btn activity-btn-medium activity-btn-lg", style: "border-radius : 2px"} %>
    </div>
    </div>
  </div>
</div>

<% a %>

 <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
              <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content" style="margin-top: 3em; width: 57em; height: 36em;">
                  <div class="row">
                    <div class="col-xs-offset-1 col-xs-10">
                    <br>
                    <h1 class="text-center">Qui sommes nous ?</h1>
                    <br>
                    <br>
                      <h5 style="font-size: 17px;"" class="text-justify" >Mon Politique est né du triste constat qu’une part de plus en plus importante   de la population se désintéresse des élections et du débat public.
                      <br>
                      <br>
                      <br>
                      Pourtant, chacun est appelé, comme dans l’agora antique, à y participer. Mais les programmes souvent indigestes et les querelles politiques étouffantes découragent et désincitent à s’engager.
                      <br>
                      <br>
                      Nous avons donc décidé de créer un outil démocratique ayant pour vocation de réconcilier les citoyens avec leur droit de vote et la vie politique. Ainsi, à travers ce site internet, nous proposons à chaque utilisateur l’opportunité de découvrir de manière ludique mais sérieuse l’ensemble des programmes des candidats à l’élection présidentielle.
                      <br>
                      <br>
                      Le principe est simple : évaluez une à une les propositions qui défilent devant votre écran pour discerner quel candidat vous correspond le mieux. A tout moment vous pourrez accéder à votre compte pour découvrir quel candidat se cache derrière les propositions que vous avez le plus appréciées.
                      <br>
                      <br>
                      <br>
                      N’oubliez pas : plus vous évaluerez de mesures, plus votre profil politique s’affinera !</h5>
                    </div>
                </div>
              </div>
            </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>

  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->


      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "Mon Candidat", opinions_path %>
            </li>
            <li>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Qui sommes-nous ?</button>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Se déconnecter") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>